### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, mkdir ''

### ISSUE THREAD

**Issue by daviian** [armin-pfaeffle/atom-minify#11]
[Enter steps to reproduce below:]
1. Started Minifying to minified file

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-minify](https://github.com/armin-pfaeffle/atom-minify) package, v0.3.0
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, mkdir ''

```
At fs.js:791

Error: ENOENT: no such file or directory, mkdir ''
  at Error (native)
  at Object.fs.mkdirSync (fs.js:791:18)
  at AtomMinifier.module.exports.AtomMinifier.ensureTargetDirectoryExists (/Users/exampleuser/.atom/packages/atom-minify/lib/minifier.coffee:166:24)
  at /Users/exampleuser/.atom/packages/atom-minify/lib/minifier.coffee:56:18
  at /Users/exampleuser/.atom/packages/atom-minify/lib/minifier.coffee:256:13
  at /Users/exampleuser/.atom/packages/atom-minify/lib/inline-parameters.coffee:16:21
  at ReadStream.<anonymous> (/Users/exampleuser/.atom/packages/atom-minify/lib/inline-parameters.coffee:39:21)
  at emitOne (events.js:77:13)
  at ReadStream.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at ReadStream.Readable.push (_stream_readable.js:109:10)
  at onread (fs.js:1734:12)
  at FSReqWrap.wrapper [as oncomplete] (fs.js:571:17)

```
### Commands

```
     -6:55.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -6:55.4.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -6:55.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:54.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -6:54.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -6:54.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -6:53.8.0 core:save (atom-text-editor.editor.is-focused)
     -5:38.6.0 core:close (atom-text-editor.editor.is-focused)
     -5:36.7.0 core:save (atom-text-editor.editor.is-focused)
     -4:55.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:37 core:save (atom-text-editor.editor.is-focused)
     -2:13.2.0 atom-minify:minify-to-min-file (atom-text-editor.editor.is-focused)
     -1:54.1.0 atom-minify:minify-direct (atom-text-editor.editor.is-focused)
     -1:47.4.0 core:undo (atom-text-editor.editor.is-focused)
     -1:45.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.6.0 atom-minify:minify-to-min-file (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "metrics",
      "welcome"
    ]
  },
  "atom-minify": {
    "checkOutputFileAlreadyExists": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.11
atom-minify, v0.3.0
autoclose-html, v0.18.0
color-picker, v2.0.11
csslint, v1.1.4
highlight-line, v0.11.0
minimap, v4.13.1

# Dev
No dev packages
```

**Comment by armin-pfaeffle** [comment]
Fixed with version 0.3.1

Thanks for you report!
