### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'd:\Documents\2015\folder\

### ISSUE THREAD

**Issue by silverspectro** [armin-pfaeffle/atom-minify#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: [atom-minify](https://github.com/armin-pfaeffle/atom-minify) package, v0.1.6
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'd:\Documents\2015\Renault_Kadjar2\dev\Desert\js\slider.min.js'

```
At fs.js:519

Error: ENOENT: no such file or directory, open 'd:\Documents\2015\Renault_Kadjar2\dev\Desert\js\slider.min.js'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:396:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
  at C:\Users\Ciro\.atom\packages\atom-minify\node_modules\node-minify\lib\node-minify.js:127:37
  at ChildProcess.exithandler (child_process.js:720:7)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Socket.<anonymous> (child_process.js:1166:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -2:02.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:55.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:51.3.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:30.6.0 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.is-focused)
     -1:30.5.0 core:save (atom-text-editor.editor.is-focused)
     -1:29.9.0 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.is-focused)
     -1:29.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  6x -1:26.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:21.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:17.8.0 core:move-up (atom-text-editor.editor.mini.is-focused)
 10x -1:15.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:14 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:14 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:00.0 atom-minify:minify-to-min-file (atom-text-editor.editor.is-focused)
     -0:39.6.0 atom-minify:js-minifier-uglifyjs2 (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
  2x -0:33 atom-minify:minify-to-min-file (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "atom-minify": {
    "jsMinifier": "UglifyJS2"
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.5
atom-minify, v0.1.6
atom-terminal-panel, v4.4.4
autoclose-html, v0.18.0
haxe, v0.6.1
language-haxe, v0.3.0
linter, v1.0.2
minimap, v4.10.0
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by armin-pfaeffle** [comment]
Will be fixed with next version, coming soon!

**Comment by davellanedam** [comment]
Also happens for CSS with "clean-css" minifier

**Comment by armin-pfaeffle** [comment]
Please try new version 0.2. I fixed the bug there.

**Comment by davellanedam** [comment]
Working great now! Thank you very much.
