### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getText' of undefined

### ISSUE THREAD

**Issue by balitax** [armin-pfaeffle/atom-minify#25]
**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [atom-minify](https://github.com/armin-pfaeffle/atom-minify) package, v0.7.3
### Stack Trace

Uncaught TypeError: Cannot read property 'getText' of undefined

```
At /Users/agus/.atom/packages/atom-minify/lib/minifier.coffee:367

TypeError: Cannot read property 'getText' of undefined
    at /Users/agus/.atom/packages/atom-minify/lib/minifier.coffee:367:85
    at /Users/agus/.atom/packages/atom-minify/lib/minifier/css/yui-css.coffee:43:25
    at ChildProcess.exithandler (child_process.js:216:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -7:21.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:21 core:save (atom-text-editor.editor.is-focused)
  7x -6:58.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:32 core:save (atom-text-editor.editor.is-focused)
  4x -5:45.8.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -5:44.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:43 core:save (atom-text-editor.editor.is-focused)
     -4:53.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -4:53.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -3:25 core:backspace (atom-text-editor.editor.is-focused)
     -3:20.2.0 core:undo (atom-text-editor.editor.is-focused)
     -3:19.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:19.3.0 atom-minify:minify-direct (atom-text-editor.editor.is-focused)
     -0:12.9.0 core:undo (atom-text-editor.editor.is-focused)
     -0:12.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:12.4.0 atom-minify:minify-direct (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
atom-minify, v0.7.3
atom-react-native-autocomplete, v0.0.26
atom-react-native-css, v1.1.2
atom-xcode, v0.1.3
language-javascript-jsx, v0.3.7
laravel, v0.7.0
laravel-snippets, v2.1.0
react-es6-snippets, v0.3.0
react-snippets, v0.4.2
source-preview-react, v0.2.0

# Dev
No dev packages
```

**Comment by armin-pfaeffle** [comment]
Can you test version 0.7.4?

**Comment by balitax** [comment]
thank you **armin-pfaeffle**, I've updated the atom-minify and no longer approach the error

<img width="790" alt="screen shot 2016-06-01 at 2 41 14 pm" src="https://cloud.githubusercontent.com/assets/1490342/15701860/ec375c1e-2806-11e6-9bf8-1738afc08127.png">
