### ISSUE TITLE
Uncaught Error: Cannot find module 'node-minify'

### ISSUE THREAD

**Issue by ghost** [armin-pfaeffle/atom-minify#5]
[Enter steps to reproduce below:]
1. save

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-minify](https://github.com/armin-pfaeffle/atom-minify) package, v0.2.0
### Stack Trace

Uncaught Error: Cannot find module 'node-minify'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:774

Error: Cannot find module 'node-minify'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at AtomMinifyView.module.exports.AtomMinifyView.minifyFile (/Users/alexmorris/.atom/packages/atom-minify/lib/atom-minify-view.coffee:196:10)
  at AtomMinifyView.module.exports.AtomMinifyView.minify (/Users/alexmorris/.atom/packages/atom-minify/lib/atom-minify-view.coffee:116:17)
  at /Users/alexmorris/.atom/packages/atom-minify/lib/atom-minify-view.coffee:48:9
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:996:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:535:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:518:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:592:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:311:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -5:04.6.0 core:copy (atom-text-editor.editor.is-focused)
     -4:52.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -4:18.2.0 core:undo (atom-text-editor.editor.is-focused)
     -4:16.6.0 core:save (atom-text-editor.editor.is-focused)
     -4:08.1.0 atom-minify:minify-to-min-file (atom-text-editor.editor.is-focused)
  4x -3:05.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:03.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:13.9.0 core:save (atom-text-editor.editor.is-focused)
     -2:11.5.0 core:undo (atom-text-editor.editor.is-focused)
  2x -2:10.7.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "atom-minify": {
    "minifyOnSave": true
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.1
atom-minify, v0.2.0
color-picker, v2.0.10
csslint, v1.1.3
emmet, v2.3.12
highlight-column, v0.5.0
highlight-line, v0.11.0
markdown-preview-plus, v1.6.0

# Dev
No dev packages
```

**Comment by ghost** [comment]
uninstall and re-install does not fix

**Comment by armin-pfaeffle** [comment]
Hey

there must be something wrong with your atom-minify installation! node-minify is not used any more and your stack-trace tells me that the code is the old one -- e.g. function `minifyFile` does not exist any more.

Can you check your installation?

**Comment by ghost** [comment]
I've cross-checked my installation at ~/.atom/packages/atom-minify after uninstall and reinstall.

My version requires and installs the 'node_modules' folder, installing from Atom.

If I uninstall and create a new folder 'atom-minify' in packages, and drag the files from github, I get an error stating that atom-minify failed to load because it couldn't find 'atom-space-pen-views'.

**Comment by ghost** [comment]
I've now fixed the problem by deleting the 'node_modules' folder in ~/.atom/packages/atom-minify/ after a clean install using Atom.

**Comment by armin-pfaeffle** [comment]
Interessting... It seems that there is an error in the update routine of Atom.

**Comment by ghost** [comment]
I hope you manage to solve the issue, if there's anything else I can help with let me know.

**Comment by armin-pfaeffle** [comment]
Well, I will wait until someone else has the same error. Perhaps there were problems with file permissions? Or can you imagine some other problem?

Another thought about this problem: I think the dependencies were resolved correctly and the CoffeeScript-files stay the old ones. That's why `node-minify` could not be found any more. But that's only a guess...

A problem already mentioned in Atom issues is that the update process in not transparent enough. You don't see any feedback. Perhaps there was an error, but you could not see that.

**Comment by AntoninSlejska** [comment]
Hi, I have the same error (on Ubuntu):

/usr/share/atom/resources/app.asar/src/pane.js:762
Hide Stack Trace
Error: Cannot find module 'node-minify'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at AtomMinifyView.module.exports.AtomMinifyView.minifyFile (/home/antoninslejska/.atom/packages/atom-minify/lib/atom-minify-view.coffee:251:18)
    at AtomMinifyView.module.exports.AtomMinifyView.minify (/home/antoninslejska/.atom/packages/atom-minify/lib/atom-minify-view.coffee:159:23)
    at /home/antoninslejska/.atom/packages/atom-minify/lib/atom-minify-view.coffee:80:28
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:996:20)

The error was thrown from the atom-minify package. This issue has already been reported.

**Comment by armin-pfaeffle** [comment]
Hm... That's strange... Can you help me finding out what's the problem?
1. Tell me which folders you can find in `/home/antoninslejska/.atom/packages/atom-minify/node_modules/`?
2. Tell me which files you can find in`/home/antoninslejska/.atom/packages/atom-minify/lib/`? And can you upload them?
3. Can you upload your package.json file from the atom-minify folder?

Thanks!

**Comment by AntoninSlejska** [comment]
Hi,
Ad. 1:
atom-space-pen-views, clean-css, csso, event-kit, node-uuid, sqwish, uglify-js, .bin

Ad. 2:
minifier, atom-minify.coffee, atom-minify-view.coffee, minifier.coffee, options.coffee
https://www.dropbox.com/s/e1pckry6dlxrs6s/lib.zip?dl=0

Ad. 3:
https://www.dropbox.com/s/0ereztayr7xpfgj/package.json?dl=0

Thanks as well.

**Comment by armin-pfaeffle** [comment]
Thank you!

There must be a cache which stores the old version of my package. Everything is correct and in your uploaded files there is no reference to `node-minify`. Tomorrow I will have closer look at the problem.
