### ISSUE TITLE
Error installing in Windows 10

### ISSUE THREAD

**Issue by jrglynn2** [armin-pfaeffle/atom-minify#56]
I cannot install the `atom-minify` package in Windows 10.  This happens on some packages but not all. For example, I was able to install `atom-beautify` and `lipsum`, but not this nor `git-log`.

Setup:
    OS:  Windows 10 Enterprise
    OS Version:  10.0.15063 Build 15063
    Atom Version:  1.28.2

I have attached the error log below - The log file this says to attach does not exist, the directory does not exist.

Thanks,

jrglynn2

Error Log:
```Installing “atom-minify@0.8.0” failed.Hide output…
C:\Users\JIM~1.GLY\AppData\Local\Temp\apm-install-dir-118618-1948-12ledww.s01wp6tj4i
`-- (empty)


npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\JIM~1.GLY\AppData\Local\Temp\apm-install-dir-118618-1948-12ledww.s01wp6tj4i\package.json'
npm WARN apm-install-dir-118618-1948-12ledww.s01wp6tj4i No description
npm WARN apm-install-dir-118618-1948-12ledww.s01wp6tj4i No repository field.
npm WARN apm-install-dir-118618-1948-12ledww.s01wp6tj4i No README data
npm WARN apm-install-dir-118618-1948-12ledww.s01wp6tj4i No license field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\jim.glynn\\AppData\\Local\\atom\\app-1.28.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\jim.glynn\\AppData\\Local\\atom\\app-1.28.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\jim.glynn\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\jim.glynn\\.atom\\.apmrc" "install" "C:\\Users\\JIM~1.GLY\\AppData\\Local\\Temp\\d-118618-1948-2t8ath.8geukgldi\\package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style" "--msvs_version=2015"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\JIM~1.GLY\AppData\Local\Temp\apm-install-dir-118618-1948-12ledww.s01wp6tj4i\node_modules\atom-minify
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\JIM~1.GLY\AppData\Local\Temp\apm-install-dir-118618-1948-12ledww.s01wp6tj4i\node_modules\atom-minify' -> 'C:\Users\JIM~1.GLY\AppData\Local\Temp\apm-install-dir-118618-1948-12ledww.s01wp6tj4i\node_modules\.atom-minify.DELETE'
npm ERR!     at moveAway (C:\Users\jim.glynn\AppData\Local\atom\app-1.28.2\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\jim.glynn\AppData\Local\atom\app-1.28.2\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at C:\Users\jim.glynn\AppData\Local\atom\app-1.28.2\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! 
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\JIM~1.GLY\AppData\Local\Temp\apm-install-dir-118618-1948-12ledww.s01wp6tj4i\node_modules\atom-minify' -> 'C:\Users\JIM~1.GLY\AppData\Local\Temp\apm-install-dir-118618-1948-12ledww.s01wp6tj4i\node_modules\.atom-minify.DELETE'
npm ERR!     at Error (native)
npm ERR!  Error: EPERM: operation not permitted, rename 'C:\Users\JIM~1.GLY\AppData\Local\Temp\apm-install-dir-118618-1948-12ledww.s01wp6tj4i\node_modules\atom-minify' -> 'C:\Users\JIM~1.GLY\AppData\Local\Temp\apm-install-dir-118618-1948-12ledww.s01wp6tj4i\node_modules\.atom-minify.DELETE'
npm ERR!     at moveAway (C:\Users\jim.glynn\AppData\Local\atom\app-1.28.2\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\jim.glynn\AppData\Local\atom\app-1.28.2\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at C:\Users\jim.glynn\AppData\Local\atom\app-1.28.2\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! 
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\JIM~1.GLY\AppData\Local\Temp\apm-install-dir-118618-1948-12ledww.s01wp6tj4i\node_modules\atom-minify' -> 'C:\Users\JIM~1.GLY\AppData\Local\Temp\apm-install-dir-118618-1948-12ledww.s01wp6tj4i\node_modules\.atom-minify.DELETE'
npm ERR!     at Error (native)
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\JIM~1.GLY\AppData\Local\Temp\apm-install-dir-118618-1948-12ledww.s01wp6tj4i\npm-debug.log
npm ERR! code 1```

**Comment by armin-pfaeffle** [comment]
Hey!

This is an installation problem with Atoms package manager `apm`. I never had such a problem and it does not come from my package. Have a look at the [forum](https://atom.io/packages) or [issue tracker](https://github.com/atom/atom/issues) if there is any similar problem.

Beside that, have you seen this line?
```npm ERR! Please try running this command again as root/Administrator.```

Can you check your installation? Have you installed Atom or a package as administrator?

**Comment by jrglynn2** [comment]
It only fails on certain packages. Some packages work fine, some get this error. I do not know enough about the differences in packages to know what the issue is, I just know that some packages install fine, others do not...

I am an administrator on my laptop, but besides that, I have tried running Atom as Administrator, and I have tried running the package install from the Administrator command line , both fail.

Is there another option for me to install this?

Thanks.

**Comment by armin-pfaeffle** [comment]
Well, you can download my package and put the package files under `C:\Users\USERNAME\.atom\packages\sass-autocompile` -- please replace `USERNAME` with your local username.

Beside that you have to execute these commands -- but I do not know exactly in which order:
```
apm rebuild atom-minify
apm install atom-minify
```
