### ISSUE TITLE
Failed to load the atom-minify package

### ISSUE THREAD

**Issue by zengbolin** [armin-pfaeffle/atom-minify#58]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: [atom-minify](https://github.com/armin-pfaeffle/atom-minify) package 0.8.0

### Stack Trace

Failed to load the atom-minify package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.29.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.29.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-minify/lib/atom-minify-view.coffee:1:17)
    at /packages/atom-minify/lib/atom-minify-view.coffee:1:1)
    at /packages/atom-minify/lib/atom-minify-view.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.29.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.29.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.29.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-minify/lib/atom-minify.coffee:4:18)
    at /packages/atom-minify/lib/atom-minify.coffee:1:1)
    at /packages/atom-minify/lib/atom-minify.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.29.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.29.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.29.0/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.29.0/resources/app/src/package.js:782:33)
    at measure (~/AppData/Local/atom/app-1.29.0/resources/app/src/package.js:143:22)
    at Package.measure (~/AppData/Local/atom/app-1.29.0/resources/app/src/package.js:88:25)
    at Package.load (~/AppData/Local/atom/app-1.29.0/resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.29.0/resources/app/src/package-manager.js:618:16)
    at config.transact (~/AppData/Local/atom/app-1.29.0/resources/app/src/package-manager.js:531:20)
    at Config.transact (~/AppData/Local/atom/app-1.29.0/resources/app/src/config.js:819:20)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.29.0/resources/app/src/package-manager.js:529:23)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.29.0/resources/app/src/atom-environment.js:833:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
advanced-open-file 0.16.8 
ask-stack 2.2.0 
file-icons 2.1.24 
git-control 0.9.0 
atom-html-preview 0.2.5 
atom-minify 0.8.0 
python-debugger 0.2.0 
quick-highlight 0.13.0 
regex-railroad-diagram 0.19.4 
simplified-chinese-menu 5.3.5 
atom-terminal-panel 4.4.4 
tree-view-git-status 1.5.0 
autocomplete-paths 2.12.2 
autocomplete-python 1.10.10 
color-picker 2.3.0 
gist-it 0.9.2 
git-log 0.4.1 
git-plus 8.0.1 
linter 2.2.0 
linter-pycodestyle 2.1.3 
markdown-preview-plus 3.5.0 
markdown-scroll-sync 2.1.2 
merge-conflicts 1.4.5 
minimap 4.29.8 
open-in-browsers 0.0.30 
platformio-ide-terminal 2.8.4 
python-tools 0.6.9 
tortoise-svn 0.5.1 
```

**Comment by CyrilCharlier** [comment]
To reproduce : Install the package manually. 

But even with the 'atom-space-pen-views' package in the package directory, i have the same issue (Of course after closing and opening Atom)

![2018-09-17 06_52_48-packages](https://user-images.githubusercontent.com/11455745/45607740-b3b50300-ba4e-11e8-930a-709196ac0cb9.png)
